//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Sat Mar 5 2022 16:56:13
//
//      Input file      : 
//      Component name  : add8c
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------

// add8

//-----------------------------------------------------------------------

module add8c(		// one stage of carry save adder for multiplier
    b,
    a,
    sum_in,
    cin,
    sum_out,
    cout
);
    input        b;		// a multiplier bit
    input [7:0]  a;		// multiplicand
    input [7:0]  sum_in;		// sums from previous stage
    input [7:0]  cin;		// carrys from previous stage
    output [7:0] sum_out;		// sums to next stage
    output [7:0] cout;		// carrys to next stage
    
    wire [7:0]   zero;
    wire [7:0]   aa;
    assign #1 aa = (b == 1'b1) ? a : 
                    zero;
    generate
        begin : xhdl1
            genvar       I;
            for (I = 0; I <= 7; I = I + 1)
            begin : stage
                
                fadd sta(
                    aa[I],
                    sum_in[I],
                    cin[I],
                    sum_out[I],
                    cout[I]
                );
            end
        end
    endgenerate
    
endmodule
