//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Sat Feb 19 2022 14:26:25
//
//      Input file      : 
//      Component name  : ssc_rom
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module ssc_rom(
    clk,
    addr,
    data
);
    input            clk;
    input [10:0]     addr;
    output reg [7:0] data;
    
    wire [7:0]       rom_data[0:2047];
    // autodetect bits 38 xx 18 xxxx 01 31
    
    always @(posedge clk)
        
            data <= rom_data[addr];
    
endmodule
